name: Enable Auto-Merge
on:
  pull_request:
    types: [labeled, synchronize, reopened]

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            // Try to enable auto-merge (it will only succeed if branch protection conditions are met)
            try {
              await github.request('PUT /repos/{owner}/{repo}/pulls/{pull_number}/auto_merge', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              core.notice(`Auto-merge enabled for #${pr.number}`);
            } catch (e) {
              core.warning(`Cannot enable auto-merge yet: ${e.message}`);
            }
