name: enable-auto-merge
"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - name: enable auto-merge
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) { core.setFailed('No pull_request in context'); return; }

            // Điều kiện bật auto-merge: nhánh bắt đầu "mel-" HOẶC có label "automerge"
            const head = pr.head?.ref ?? '';
            const labels = (pr.labels ?? []).map(l => l?.name ?? '');
            const shouldEnable = head.startsWith('mel-') || labels.includes('automerge');
            if (!shouldEnable) {
              core.info(`Skip enable: head=${head} labels=[${labels.join(',')}]`);
              return;
            }

            // Thử REST trước
            try {
              await github.request('PUT /repos/{owner}/{repo}/pulls/{pull_number}/auto_merge', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              core.notice(`REST enabled auto-merge for #${pr.number}`);
              return;
            } catch (e) {
              core.warning(`REST failed: ${e.message}. Fallback to GraphQL...`);
            }

            // Fallback GraphQL
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            const nodeId = data.node_id;

            await github.graphql(
              `mutation($id:ID!,$method:PullRequestMergeMethod!){
                 enablePullRequestAutoMerge(input:{pullRequestId:$id, mergeMethod:$method}){ clientMutationId }
               }`,
              { id: nodeId, method: 'SQUASH' }
            );
            core.notice(`GraphQL enabled auto-merge for #${pr.number}`);
