name: Enable Auto-Merge
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  enable:
    if: startsWith(github.head_ref, 'mel-') || contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            try {
              await github.request('PUT /repos/{owner}/{repo}/pulls/{pull_number}/auto_merge', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              core.notice(`Auto-merge enabled for #${pr.number}`);
            } catch (e) {
              core.warning(`Cannot enable auto-merge: ${e.message}. Check Settings → General → Pull Requests → Allow auto-merge is ON, and branch protection conditions.`);
            }
