name: Open PR on push
on:
  push:
    branches:
      - 'mel-*'

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      # Tạo PR tự động dùng GitHub Script
      - uses: actions/github-script@v7
        with:
          script: |
            const base = "main"; // hoặc 'develop'
            const head = context.ref.replace("refs/heads/","");

            // Check if PR already exists
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              head: `${context.repo.owner}:${head}`
            });
            if (prs.length) {
              core.info(`PR already exists: #${prs[0].number}`);
              return;
            }

            // Extract issue key from branch name
            const m = head.match(/(MEL-\d+)/i);
            const issueKey = m ? m[1].toUpperCase() : null;

            const title = issueKey ? `${issueKey} ${head.replace(/^[^-]+-/, "").replace(/-/g, " ")}` : `PR ${head}`;
            const body = `Auto-opened PR for branch \`${head}\`${issueKey ? `\n\nLinked: ${issueKey}` : ""}\n\nChecklist:\n- [ ] Tests pass\n- [ ] Docs updated\n`;

            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              head,
              base,
              body,
            });

            core.notice(`Opened PR #${pr.number}`);
